/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Proccess.NhaCungCap;
import javax.swing.DefaultComboBoxModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Proccess.NhaCungCapDao;
import Proccess.NhaCungCap;
import Proccess.DataNhanVien;
import Proccess.HoaDon;
import Proccess.HoaDonDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.DefaultComboBoxModel;
import Proccess.SanPham;
import Proccess.SanPhamDao;
import Proccess.NhanVie;
import Proccess.NhanVienDao;
import java.text.ParseException;
import Proccess.KhachHang;
import Proccess.KhachHangDao;
import java.text.SimpleDateFormat;

/**
 *
 * @author tran dat
 */
public class QLHoaDon extends javax.swing.JFrame {

    SimpleDateFormat FDate = new SimpleDateFormat("yyyy-MM-dd");
    NhanVienDao nvDao = new NhanVienDao();
    KhachHangDao khDao = new KhachHangDao();
    HoaDonDao hdDao = new HoaDonDao();

    /**
     * Creates new form QLHoaDon
     */
    public QLHoaDon() {
        initComponents();
        getCboNhanVien();
        getCboKhachHang();
        fillData();
    }

    public void getCboNhanVien() {
        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cbMaNV.getModel();
        for (NhanVie nv : nvDao.getAll()) {
            cboModel.addElement(nv);
        }
    }

    public void getCboKhachHang() {
        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cbMaKH.getModel();
        for (KhachHang kh : khDao.getAll()) {
            cboModel.addElement(kh);
        }
    }

    public void fillData() {
        DefaultTableModel tbModel = (DefaultTableModel) tblHD.getModel();
        tbModel.setRowCount(0);
        for (HoaDon hd : hdDao.getAll()) {
            Object dataRow[] = new Object[4];
            dataRow[0] = hd.getMaHD();
            dataRow[1] = hd.getKH().getMaKH();
            dataRow[2] = hd.getNV().getMaNV();
            dataRow[3] = FDate.format(hd.getNgayHD());
            tbModel.addRow(dataRow);
        }
    }

    public HoaDon getModel() throws ParseException {

        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHD.getText());
        // NhaCungCap ncc = nccDao.getByName(cbNCC.getSelectedItem().toString());
        KhachHang kh = khDao.getByName(cbMaKH.getSelectedItem().toString());
        NhanVie nv = nvDao.getByName(cbMaNV.getSelectedItem().toString());
        hd.setNgayHD(FDate.parse(txtDate.getText()));
        //sp.setTenHH(txtTenSP.getText());
        //sp.setGiaBan(Integer.parseInt(txtGiaBan.getText()));
        //sp.setDVT(txtDVT.getText());
        //NhaCungCap ncc = nccDao.getByName(cbNCC.getSelectedItem().toString());
        //sp.setMaNCC(ncc);

        return hd;

    }
        public void LamMoiFrom() {
        txtMaHD.setText("");
        cbMaKH.setSelectedItem(null);
        cbMaNV.setSelectedItem(null);
        txtDate.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        cbMaKH = new javax.swing.JComboBox<>();
        cbMaNV = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHD = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bảng Hóa Đơn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã Hóa Đơn");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã Khách Hàng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã Nhân Viên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ngày Bán");

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        tblHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Khách Hàng", "Mã Nhân Viên", "Ngày Bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHD);

        btnBack.setText("Quay Lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setText("Bảng Chi Tiết Hóa Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHD)
                            .addComponent(cbMaKH, 0, 148, Short.MAX_VALUE)
                            .addComponent(cbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnBack)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(txtMaHD.getText().equals("") || txtDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đầy Đủ Thông Tin");
        }
        else{ String sql = "insert into HoaDon (MaHD,makh,manv,ngaylaphd) Values (?,?,?,?)";
        try (
                Connection conn = DataNhanVien.openConnetion();
                PreparedStatement ps = conn.prepareStatement(sql);) {
            String MaHD = txtMaHD.getText();
           String MaKH =  cbMaKH.getSelectedItem().toString();
           String MaNV =  cbMaNV.getSelectedItem().toString();
            String Ngay = txtDate.getText();
            ps.setString(1, MaHD);
            ps.setString(2, MaKH);
            ps.setString(3, MaNV);
            ps.setString(4, Ngay);
            if(ps.executeUpdate()>0){
                 System.out.println("Them Thanh Cong!");
                 fillData();
                 LamMoiFrom();
             }
        } 
         catch (Exception ex) {
           System.out.println("loi 10: " +ex.getMessage());
        }}
        
        /*StringBuilder sb = new StringBuilder();
        if (txtMaHD.getText().equals("") || txtDate.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đầy Đủ Thông Tin");

        } else {

            try {
                HoaDon hd = getModel();
                 //string mancc = txtmancc.gettext(); 
            //ps.setstring(1, 
                if (hdDao.add(hd) > 0) {
                    JOptionPane.showMessageDialog(this, "Lưu Thành Công! ");
                    fillData();
                    LamMoiFrom();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi 6 hd:" + ex.getMessage());
            }
        }*/
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDMouseClicked
        // TODO add your handling code here:
        int row = tblHD.getSelectedRow();
        if (row >= 0) {
            txtMaHD.setText(tblHD.getValueAt(row, 0).toString());
            cbMaKH.getModel().setSelectedItem(tblHD.getValueAt(row, 1));
            cbMaNV.getModel().setSelectedItem(tblHD.getValueAt(row, 2));
            txtDate.setText(tblHD.getValueAt(row, 3).toString());
           
        }
    }//GEN-LAST:event_tblHDMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
                if (txtMaHD.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đối tượng để xóa");

        } else {
            txtMaHD.setBackground(Color.white);
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb);
                return;
            }
            if (JOptionPane.showConfirmDialog(this, "Xác Nhận Xóa Sản Phẩm") == JOptionPane.NO_OPTION) {
                return;
            }
            try {
                hdDao.delete(txtMaHD.getText());
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                fillData();
                LamMoiFrom();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi:" + ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
   String sql = "update HOADON set MaKH=?,MaNV=?,NgayLapHD=? where MaHD=?";
        try (
                Connection conn = DataNhanVien.openConnetion();
                PreparedStatement ps = conn.prepareStatement(sql);) {
            String MaHD = txtMaHD.getText();
           String MaKH =  cbMaKH.getSelectedItem().toString();
           String MaNV =  cbMaNV.getSelectedItem().toString();
            String Ngay = txtDate.getText();
            ps.setString(4, MaHD);
            ps.setString(1, MaKH);
            ps.setString(2, MaNV);
            ps.setString(3, Ngay);
            if(ps.executeUpdate()>0){
                 System.out.println("Sửa Thanh Cong!");
                 fillData();
                 LamMoiFrom();
             }
        } 
         catch (Exception ex) {
           System.out.println("loi 11: " +ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmMain frm = new frmMain();
        frm.show();
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        fillData();
        LamMoiFrom();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        QLCTHoaDon ql;
        try {
            ql = new QLCTHoaDon();
             ql.show();
        dispose();
        } catch (Exception ex) {
            Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMaKH;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHD;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMaHD;
    // End of variables declaration//GEN-END:variables
}
